version: "3.4"
services:
  app:
    build:
      context: .
      target: base
      cache_from:
        - ${IMAGE_BUILD:-snowballgr-ui:latest}
    image: ${IMAGE_BUILD:-snowballgr-ui:latest}
    command: ["bash", "-c", "yarn && yarn start"]
    stdin_open: true
    ports:
      - 3000:3000
    env_file: .env
    volumes:
      - .:/app/
